function results = rlc_fractional_study(doPlots, outputDirectory)
%RLC_FRACTIONAL_STUDY Reproduce the ideal fractional RLC numerical study.
%   RESULTS = RLC_FRACTIONAL_STUDY runs the complete study and saves figures
%   and CSV files in ./matlab_results. No optional MATLAB toolbox is needed.
%   RESULTS = RLC_FRACTIONAL_STUDY(false) saves CSV files without plotting.
%   RESULTS = RLC_FRACTIONAL_STUDY(true, 'my_results') selects the output path.
%
%   Model, with u=t/tau, x=v_C/V0 and y=Z0*i/V0:
%       D_C^alpha x = y,   D_C^alpha y = 1 - x - rho*y,
%       x(0)=y(0)=0.
%   At alpha=1, R=10 ohm, L=10 mH and C=100 microfarad. At alpha<1 the
%   elements obey ideal fractional constitutive laws; this is a model study,
%   not a hardware experiment. D_C denotes the Caputo derivative.
%
%   Backward-Euler convolution quadrature (full, untruncated history):
%       w_j = (1-(1+alpha)/j)*w_{j-1}, w_0=1,
%       z_n = (I-h^alpha*A)^(-1) *
%             (h^alpha*b - sum_{j=1}^n w_j*z_{n-j}).
%   The zero initial states make the CQ Caputo correction vanish. The same
%   recurrence at alpha=1 is ordinary backward Euler, not an exact solver.
%   Work grows quadratically with U/h; the default fine mesh has 24001 nodes.
%
%   Settling times are last-exit estimates on the finite 0--60 ms record.
%   Both the first in-band sample after the last exit and a linearly
%   interpolated boundary crossing are reported. NaN means the requested
%   quantity was not observed by the horizon. A finite record does not prove
%   that the response will remain inside the band for all future time.
%
%   This delivered script was statically reviewed, but was not run in MATLAB
%   in the preparation environment. The accompanying Python implementation
%   generated the paper's plots and was checked by independent inversion.

if nargin < 1 || isempty(doPlots)
    doPlots = true;
end
if nargin < 2 || isempty(outputDirectory)
    outputDirectory = fullfile(pwd, 'matlab_results');
end
if ~isscalar(doPlots)
    error('doPlots must be a scalar logical or numeric value.');
end
if ~exist(outputDirectory, 'dir')
    mkdir(outputDirectory);
end

alphaValues = [0.8, 0.9, 1.0];
hValues = [0.01, 0.005, 0.0025];
U = 60;
tau = 1e-3;             % seconds
Z0 = 10;               % ohm
V0 = 1;                % volt
rho = 1;               % R/Z0
A = [0, 1; -1, -rho];
b = [0; 1];
colors = [0.00, 0.32, 0.62; 0.82, 0.29, 0.10; 0.20, 0.50, 0.26];
labels = {'alpha = 0.8', 'alpha = 0.9', 'alpha = 1.0'};

results = struct;
results.parameters = struct('alpha', alphaValues, 'h', hValues, 'U', U, ...
    'tau_s', tau, 'Z0_ohm', Z0, 'V0_V', V0, 'rho', rho, 'A', A, 'b', b);
results.outputDirectory = outputDirectory;
results.mesh = cell(numel(alphaValues), numel(hValues));

fprintf('Running full-history convolution quadrature; this may take several minutes.\n');
for ia = 1:numel(alphaValues)
    for ih = 1:numel(hValues)
        fprintf('  alpha = %.1f, h = %.4f\n', alphaValues(ia), hValues(ih));
        [u, z] = solveCQ(alphaValues(ia), hValues(ih), U, A, b);
        run = struct('alpha', alphaValues(ia), 'h', hValues(ih), ...
            'u', u, 't_s', tau*u, 'z', z, 'vC_V', V0*z(1,:), ...
            'i_A', (V0/Z0)*z(2,:));
        run.metrics = responseMetrics(u, z, tau, V0, Z0);
        results.mesh{ia, ih} = run;
    end
end
results.fine = results.mesh(:, end);

% Closed-form classical reference, independent of the numerical recurrence.
wd = sqrt(1 - rho^2/4);
classicalRows = zeros(numel(hValues), 5);
for ih = 1:numel(hValues)
    run = results.mesh{end, ih};
    e = exp(-rho*run.u/2);
    xExact = 1 - e.*(cos(wd*run.u) + rho/(2*wd)*sin(wd*run.u));
    yExact = e.*sin(wd*run.u)/wd;
    classicalRows(ih,:) = [run.h, max(abs(run.z(1,:)-xExact))*V0, ...
        max(abs(run.z(2,:)-yExact))*(V0/Z0), ...
        abs(run.z(1,end)-xExact(end))*V0, ...
        abs(run.z(2,end)-yExact(end))*(V0/Z0)];
end
results.classicalError = classicalRows;

% Compare each coarser mesh with the fine mesh at common time nodes.
meshRows = zeros(numel(alphaValues)*(numel(hValues)-1), 5);
k = 0;
for ia = 1:numel(alphaValues)
    fine = results.mesh{ia, end};
    for ih = 1:numel(hValues)-1
        coarse = results.mesh{ia, ih};
        stride = round(coarse.h/fine.h);
        if abs(stride*fine.h-coarse.h) > 1e-12
            error('The meshes must have integer step-size ratios.');
        end
        zFineAtCoarseNodes = fine.z(:, 1:stride:end);
        k = k+1;
        meshRows(k,:) = [alphaValues(ia), coarse.h, fine.h, ...
            V0*max(abs(coarse.z(1,:)-zFineAtCoarseNodes(1,:))), ...
            (V0/Z0)*max(abs(coarse.z(2,:)-zFineAtCoarseNodes(2,:)))];
    end
end
results.meshComparison = meshRows;

% Independent Laplace inversion references (mpmath, de Hoog method, 35 dps).
% These fixed values can be regenerated by the accompanying simulation.py;
% no inverse-Laplace toolbox is required to check them in MATLAB. Columns
% correspond to u = 0.25, 1, 2, 4, 10, 20, 30, 60; rows to alpha values.
referenceU = [0.25, 1, 2, 4, 10, 20, 30, 60];
referenceX = [ ...
    0.06422381780090552, 0.39455724340331516, 0.7280683832680246, ...
    0.9431913722169257, 0.9673940957944175, 0.9804893684730872, ...
    0.9857806392600282, 0.9917877079272146; ...
    0.043548073176072934, 0.3717784882703595, 0.7902265255788807, ...
    1.040258344939488, 0.9865733776642929, 0.9930523069883991, ...
    0.9951228895166322, 0.997368438662134; ...
    0.028653632637901032, 0.3402998466082983, 0.8494256348541124, ...
    1.1531227684140493, 1.0021701167393262, 1.0000242939948036, ...
    0.9999996652004047, 0.999999999999958];
laplaceRows = zeros(numel(alphaValues)*numel(hValues), 3);
k = 0;
for ia = 1:numel(alphaValues)
    for ih = 1:numel(hValues)
        run = results.mesh{ia, ih};
        indices = round(referenceU/run.h)+1;
        if any(abs(run.u(indices)-referenceU) > 1e-10)
            error('Reference times must lie on every numerical mesh.');
        end
        k = k+1;
        laplaceRows(k,:) = [alphaValues(ia), run.h, ...
            V0*max(abs(run.z(1,indices)-referenceX(ia,:)))];
    end
end
results.laplaceReference = struct('u', referenceU, 'x', referenceX, ...
    'method', 'mpmath inverse Laplace, de Hoog, 35 decimal digits');
results.laplaceValidation = laplaceRows;

fHz = logspace(0, 4, 1000);
H = zeros(numel(alphaValues), numel(fHz));
for ia = 1:numel(alphaValues)
    q = (1i*2*pi*fHz*tau).^alphaValues(ia);
    H(ia,:) = 1./(q.^2+rho*q+1);
end
results.frequency = struct('f_Hz', fHz, 'H', H, ...
    'magnitude_dB', 20*log10(abs(H)), ...
    'phase_deg', (180/pi)*unwrap(angle(H), [], 2));

writeMetricsCSV(fullfile(outputDirectory, 'metrics.csv'), results.fine);
writeNumericCSV(fullfile(outputDirectory, 'classical_error.csv'), ...
    'h_dimensionless,max_vC_error_V,max_i_error_A,final_vC_error_V,final_i_error_A', ...
    classicalRows);
writeNumericCSV(fullfile(outputDirectory, 'mesh_validation.csv'), ...
    'alpha,h_coarse_dimensionless,h_fine_dimensionless,max_vC_difference_V,max_i_difference_A', ...
    meshRows);
writeNumericCSV(fullfile(outputDirectory, 'laplace_validation.csv'), ...
    'alpha,h_dimensionless,max_reference_grid_vC_error_V', laplaceRows);

% Save all states, meshes and metadata so that CSVs and figures are traceable.
save(fullfile(outputDirectory, 'results.mat'), 'results');

if doPlots
    makeFigures(results, colors, labels);
end
fprintf('Results saved in %s\n', outputDirectory);
end

function [u, z] = solveCQ(alpha, h, U, A, b)
N = round(U/h);
if abs(N*h-U) > 1e-10
    error('U/h must be an integer.');
end
u = (0:N)*h;
w = zeros(N+1, 1);
w(1) = 1;
for j = 1:N
    w(j+1) = (1-(1+alpha)/j)*w(j);
end
ha = h^alpha;
G = (eye(2)-ha*A)\eye(2);  % Compute the constant 2-by-2 inverse once.
z = zeros(2, N+1);
for n = 1:N
    history = z(:, n:-1:1)*w(2:n+1);
    z(:, n+1) = G*(ha*b-history);
end
end

function m = responseMetrics(u, z, tau, V0, Z0)
x = z(1,:);
[peak, index] = max(x);
m.overshoot_percent_0_60ms = 100*max(0, peak-1);
if peak > 1
    m.peak_time_ms = 1e3*tau*u(index);
else
    m.peak_time_ms = NaN;
end
t10 = firstCrossing(u, x, 0.1);
t90 = firstCrossing(u, x, 0.9);
m.rise_10_90_ms = 1e3*tau*(t90-t10);
[sampled, interpolated] = lastExit(u, x, 0.02);
m.settling_2pct_sampled_ms = 1e3*tau*sampled;
m.settling_2pct_interpolated_ms = 1e3*tau*interpolated;
[sampled, interpolated] = lastExit(u, x, 0.01);
m.settling_1pct_sampled_ms = 1e3*tau*sampled;
m.settling_1pct_interpolated_ms = 1e3*tau*interpolated;
m.x30 = interp1(u, z(1,:), 30, 'linear');
m.x60 = z(1,end);
m.y30 = interp1(u, z(2,:), 30, 'linear');
m.y60 = z(2,end);
m.vC_30ms_V = V0*m.x30;
m.vC_60ms_V = V0*m.x60;
m.i_30ms_A = (V0/Z0)*m.y30;
m.i_60ms_A = (V0/Z0)*m.y60;
end

function crossing = firstCrossing(u, x, level)
index = find(x >= level, 1, 'first');
if isempty(index)
    crossing = NaN;
elseif index == 1
    crossing = u(1);
else
    crossing = u(index-1) + (level-x(index-1))* ...
        (u(index)-u(index-1))/(x(index)-x(index-1));
end
end

function [sampled, interpolated] = lastExit(u, x, tolerance)
errorMagnitude = abs(x-1);
index = find(errorMagnitude > tolerance, 1, 'last');
if isempty(index)
    sampled = u(1);
    interpolated = u(1);
elseif index == numel(u)
    sampled = NaN;
    interpolated = NaN;
else
    sampled = u(index+1);
    interpolated = u(index) + (tolerance-errorMagnitude(index))* ...
        (u(index+1)-u(index))/(errorMagnitude(index+1)-errorMagnitude(index));
end
end

function writeMetricsCSV(filename, fine)
fields = {'overshoot_percent_0_60ms', 'peak_time_ms', 'rise_10_90_ms', ...
    'settling_2pct_sampled_ms', 'settling_2pct_interpolated_ms', ...
    'settling_1pct_sampled_ms', 'settling_1pct_interpolated_ms', ...
    'x30', 'x60', 'y30', 'y60', 'vC_30ms_V', 'vC_60ms_V', ...
    'i_30ms_A', 'i_60ms_A'};
header = 'alpha';
for j = 1:numel(fields)
    header = [header, ',', fields{j}]; %#ok<AGROW>
end
rows = zeros(numel(fine), numel(fields)+1);
for ia = 1:numel(fine)
    rows(ia,1) = fine{ia}.alpha;
    for j = 1:numel(fields)
        rows(ia,j+1) = fine{ia}.metrics.(fields{j});
    end
end
writeNumericCSV(filename, header, rows);
end

function writeNumericCSV(filename, header, rows)
fid = fopen(filename, 'w');
if fid == -1
    error('Unable to open CSV file: %s', filename);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '%s\n', header);
for k = 1:size(rows,1)
    fprintf(fid, '%.12g', rows(k,1));
    fprintf(fid, ',%.12g', rows(k,2:end));
    fprintf(fid, '\n');
end
end

function makeFigures(results, colors, labels)
fine = results.fine;
out = results.outputDirectory;
V0 = results.parameters.V0_V;

fig = figure('Color', 'w', 'Name', 'Fractional RLC transient');
subplot(2,1,1); hold on;
for ia = 1:numel(fine)
    plot(1e3*fine{ia}.t_s, fine{ia}.vC_V, 'Color', colors(ia,:), 'LineWidth', 1.4);
end
plot([0,12], [V0,V0], 'k:', 'HandleVisibility', 'off');
xlim([0,12]); grid on;
ylabel('Capacitor voltage v_C (V)');
legend(labels, 'Location', 'southeast');
subplot(2,1,2); hold on;
for ia = 1:numel(fine)
    plot(1e3*fine{ia}.t_s, 1e3*fine{ia}.i_A, 'Color', colors(ia,:), 'LineWidth', 1.4);
end
xlim([0,12]); grid on;
xlabel('Time t (ms)'); ylabel('Series current i (mA)');
saveFigure(fig, out, 'transient');

fig = figure('Color', 'w', 'Name', 'Fractional RLC tail'); hold on;
for ia = 1:numel(fine)
    plot(1e3*fine{ia}.t_s, 100*(fine{ia}.z(1,:)-1), ...
        'Color', colors(ia,:), 'LineWidth', 1.4);
end
for tolerance = [-2,-1,1,2]
    plot([5,60], [tolerance,tolerance], 'k:', 'HandleVisibility', 'off');
end
xlim([5,60]); ylim([-5.5,9]); grid on;
xlabel('Time t (ms)'); ylabel('Voltage error 100(v_C/V_0 - 1) (%)');
legend(labels, 'Location', 'southeast');
saveFigure(fig, out, 'tail');

fHz = results.frequency.f_Hz;
fig = figure('Color', 'w', 'Name', 'Fractional RLC frequency response');
subplot(2,1,1); hold on;
for ia = 1:numel(fine)
    semilogx(fHz, results.frequency.magnitude_dB(ia,:), ...
        'Color', colors(ia,:), 'LineWidth', 1.4);
end
set(gca, 'XScale', 'log'); grid on;
ylabel('Voltage gain |H| (dB)'); legend(labels, 'Location', 'southwest');
subplot(2,1,2); hold on;
for ia = 1:numel(fine)
    semilogx(fHz, results.frequency.phase_deg(ia,:), ...
        'Color', colors(ia,:), 'LineWidth', 1.4);
end
set(gca, 'XScale', 'log'); grid on;
xlabel('Frequency f (Hz)'); ylabel('Phase (degree)');
saveFigure(fig, out, 'frequency');

fig = figure('Color', 'w', 'Name', 'Fractional RLC mesh validation'); hold on;
rows = results.laplaceValidation;
for ia = 1:numel(fine)
    select = abs(rows(:,1)-fine{ia}.alpha) < 1e-12;
    if fine{ia}.alpha == 1
        plotH = results.classicalError(:,1);
        plotError = results.classicalError(:,2);
    else
        plotH = rows(select,2);
        plotError = rows(select,3);
    end
    loglog(plotH, plotError, '-o', ...
        'Color', colors(ia,:), 'LineWidth', 1.4, 'MarkerSize', 6);
end
h = results.parameters.h;
guide = rows(1,3)*(h/h(1));
loglog(h, guide, 'k--', 'LineWidth', 1.2);
set(gca, 'XScale', 'log', 'YScale', 'log'); grid on;
xlabel('Dimensionless step h = Delta t / tau');
ylabel('Maximum voltage error (V)');
legend([labels, {'O(h) guide'}], 'Location', 'northwest');
title({'Fractional: eight independent Laplace samples', ...
       'Classical: exact solution at every grid node'});
saveFigure(fig, out, 'convergence');
end

function saveFigure(fig, directory, basename)
set(fig, 'PaperPositionMode', 'auto');
print(fig, fullfile(directory, [basename,'.png']), '-dpng', '-r200');
print(fig, fullfile(directory, [basename,'.pdf']), '-dpdf');
end
